version: "3.8"

services:

  #
  # xion-rehearsal-1
  #

  add-gentx:
    image: burntnetwork/xion:0.3.4
    platform: linux/amd64
    command:
      - /bin/sleep
      - infinity
    environment:
      MONIKER: "🔥 ahi.burnt.com 🔥"
      CHAIN_ID: "xion-rehearsal-1"
      KEYNAME: "ahi.burnt.com"
      GENESIS_AMOUNT: "1000000000000uxion"
      COMMISSION_MAX_RATE: "0.10"
      COMMISSION_MAX_CHANGE_RATE: "0.01"
      COMMISSION_RATE: "0.10"
    volumes:
      - ./.docker/home:/home/xiond/.xiond
      - ./.docker/scripts:/tmp/scripts
      - ./testnets/xion-rehearsal-1:/tmp/testnet

  validate-genesis:
    image: burntnetwork/xion:0.3.4
    platform: linux/amd64
    command:
      - /tmp/scripts/validate-genesis.sh
    environment:
      MONIKER: "burnt"
      CHAIN_ID: "xion-rehearsal-1"
    volumes:
      - ./.docker/home:/home/xiond/.xiond
      - ./.docker/scripts:/tmp/scripts
      - ./testnets/xion-rehearsal-1:/tmp/testnet

  generate-hashes:
    image: debian:bookworm-20240130-slim
    platform: linux/amd64
    command:
      - /tmp/scripts/generate-hashes.sh
    volumes:
      - ./.docker/home:/home/xiond/.xiond
      - ./.docker/scripts:/tmp/scripts
      - ./testnets/xion-rehearsal-1:/tmp/testnet

  verify-hashes:
    image: debian:bookworm-20240130-slim
    platform: linux/amd64
    command:
      - /tmp/scripts/verify-hashes.sh
    volumes:
      - ./.docker/home:/home/xiond/.xiond
      - ./.docker/scripts:/tmp/scripts
      - ./testnets/xion-rehearsal-1:/tmp/testnet

  #
  # xion-testnet-1
  #

  validate-genesis-xion-testnet-1:
    image: burntnetwork/xion:0.1.0
    platform: linux/amd64
    command:
      - /tmp/scripts/validate-genesis.sh
    environment:
      MONIKER: "burnt"
      CHAIN_ID: "xion-testnet-1"
    volumes:
      - ./.docker/home:/home/xiond/.xiond
      - ./.docker/scripts:/tmp/scripts
      - ./testnets/xion-testnet-1:/tmp/testnet

  generate-hashes-xion-testnet-1:
    image: debian:bookworm-20240130-slim
    platform: linux/amd64
    command:
      - /tmp/scripts/generate-hashes.sh
    volumes:
      - ./.docker/home:/home/xiond/.xiond
      - ./.docker/scripts:/tmp/scripts
      - ./testnets/xion-testnet-1:/tmp/testnet

  verify-hashes-xion-testnet-1:
    image: debian:bookworm-20240130-slim
    platform: linux/amd64
    command:
      - /tmp/scripts/verify-hashes.sh
    volumes:
      - ./.docker/home:/home/xiond/.xiond
      - ./.docker/scripts:/tmp/scripts
      - ./testnets/xion-testnet-1:/tmp/testnet
