---
name: Verify Genesis Hashes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    name: Verify Genesis Hashes
    runs-on: ubuntu-latest
    environment: CI

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Verify genesis hashes
        shell: bash
        run: |
          docker compose up --exit-code-from verify-hashes
